//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaoCao
    {
        public int MaBaoCao { get; set; }
        public string TieuDe { get; set; }
        public string NoiDung { get; set; }
        public string LoaiBaoCao { get; set; }
        public Nullable<int> MaNguoiTao { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
    
        public virtual NguoiDung NguoiDung { get; set; }
    }
}
