//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Diem
    {
        public int MaDiem { get; set; }
        public Nullable<int> MaHocSinh { get; set; }
        public Nullable<int> MaKhoaHoc { get; set; }
        public Nullable<decimal> DiemGiuaKy { get; set; }
        public Nullable<decimal> DiemCuoiKy { get; set; }
        public Nullable<decimal> DiemTongKet { get; set; }
        public string GhiChu { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
    
        public virtual HocSinh HocSinh { get; set; }
        public virtual KhoaHoc KhoaHoc { get; set; }
    }
}
