//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GuiThongBao
    {
        public int MaThongBao { get; set; }
        public int MaNguoiDung { get; set; }
        public Nullable<bool> DaDoc { get; set; }
    
        public virtual NguoiDung NguoiDung { get; set; }
        public virtual ThongBao ThongBao { get; set; }
    }
}
