//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HocPhi
    {
        public int MaHocPhi { get; set; }
        public Nullable<int> MaHocSinh { get; set; }
        public Nullable<int> MaKhoaHoc { get; set; }
        public decimal SoTien { get; set; }
        public Nullable<System.DateTime> NgayDong { get; set; }
        public string TrangThai { get; set; }
    
        public virtual HocSinh HocSinh { get; set; }
        public virtual KhoaHoc KhoaHoc { get; set; }
    }
}
