//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhanCongGiaoVien
    {
        public int MaPhanCong { get; set; }
        public Nullable<int> MaLop { get; set; }
        public Nullable<int> MaGiaoVien { get; set; }
        public Nullable<System.DateTime> NgayPhanCong { get; set; }
    
        public virtual GiaoVien GiaoVien { get; set; }
        public virtual LopHoc LopHoc { get; set; }
    }
}
